name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t node-ci-cd-demo:latest .

      - name: Run Docker container (optional test)
        run: docker run -d -p 3000:3000 node-ci-cd-demo:latest
